# Generated by Django 3.1.2 on 2020-10-12 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(
                    decimal_places=2, max_digits=5,
                    validators=[django.core.validators.MinValueValidator(0)])),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='pizza.pizza')),
                ('topping', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='pizza.topping')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(through='pizza.Structure',
                                         to='pizza.Topping'),
        ),
    ]
