# Generated by Django 3.1.2 on 2020-10-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20201011_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='votes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Voters',
        ),
    ]
