# Generated by Django 3.1.2 on 2020-10-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_auto_20201011_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3.99,
                                      max_digits=5),
            preserve_default=False,
        ),
    ]
