# Generated by Django 3.1.2 on 2020-10-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_pizza_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pizza',
            constraint=models.CheckConstraint(check=models.Q(price__gt='0'),
                                              name='price_gt_0'),
        ),
    ]
